on: [push]
name: Azure ARM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      wiz_auth_url: ${{ secrets.WIZ_AUTH_URL }}
      wiz_endpoint_url:  ${{ secrets.WIZ_ENDPOINT_URL }}
      wiz_client_id:  ${{ secrets.WIZ_CLIENT_ID }}
      wiz_client_secret: ${{ secrets.WIZ_CLIENT_SECRET }}
      azure_loganalytics_workspace_id: ${{ secrets.AZURE_LOGANALYTICS_WORKSPACE_ID }}
      azure_loganalytics_workspace_sharedkey: ${{ secrets.AZURE_LOGANALYTICS_WORKSPACE_SHAREDKEY }}
      azure_loganalytics_resource_id: ${{ secrets.AZURE_LOGANALYTICS_RESOURCE_ID }}
      
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: ./prod.bicepparam
        failOnStdErr: false